# Generated by Django 2.2.6 on 2019-10-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_Names', models.CharField(blank=True, max_length=100, null=True)),
                ('Birthday', models.DateField(blank=True, null=True)),
                ('Number_Phone', models.CharField(blank=True, max_length=14, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('Suburn', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
