# Generated by Django 2.2.6 on 2019-10-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
