# Generated by Django 2.2.6 on 2019-10-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0004_auto_20191024_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='birthday',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
