# Generated by Django 2.2.6 on 2019-10-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0005_auto_20191024_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
