# Generated by Django 2.2.6 on 2019-11-21 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0009_auto_20191112_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='pacientes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pruebas.paciente', verbose_name='pacientes'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='precion_d',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='precion_s',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
