# Generated by Django 2.2.6 on 2019-11-26 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0011_auto_20191126_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='peso',
        ),
    ]
