# Generated by Django 2.2.6 on 2019-11-28 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0013_expediente_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='notesexpedient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('hora', models.CharField(blank=True, max_length=10, null=True)),
                ('expedientes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pruebas.expediente', verbose_name='expedientes')),
            ],
        ),
    ]
