# Generated by Django 2.2.6 on 2019-12-02 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0014_notesexpedient'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicina',
            name='docis',
            field=models.TextField(blank=True, null=True, verbose_name='Docis Recomendada'),
        ),
        migrations.AlterField(
            model_name='notesexpedient',
            name='expedientes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pruebas.expediente', verbose_name='expedientes'),
        ),
    ]
