# Generated by Django 2.2.6 on 2019-12-03 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0016_auto_20191202_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='actualizacion',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='hoara',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='notesexpedient',
            name='expedientes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pruebas.expediente', verbose_name='expedientes'),
        ),
    ]
