# Generated by Django 2.2.8 on 2019-12-26 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0019_auto_20191211_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='emergencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=13, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='notesexpedient',
            name='expedientes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pruebas.expediente', verbose_name='expedientes'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='encaso_de_emergencia',
            field=models.ManyToManyField(to='pruebas.emergencia', verbose_name='Emergencia'),
        ),
    ]
