# Generated by Django 2.2.8 on 2019-12-31 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0020_auto_20191226_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesexpedient',
            name='expedientes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pruebas.expediente', verbose_name='expedientes'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='encaso_de_emergencia',
            field=models.ManyToManyField(blank=True, null=True, to='pruebas.emergencia', verbose_name='Emergencia'),
        ),
    ]
