# Generated by Django 2.2.6 on 2019-11-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('formula', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='paciente',
            new_name='patient',
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.CharField(blank=True, max_length=100, null=True)),
                ('altura', models.CharField(blank=True, max_length=100, null=True)),
                ('pulso', models.CharField(blank=True, max_length=100, null=True)),
                ('respiracion', models.CharField(blank=True, max_length=100, null=True)),
                ('temperatura', models.CharField(blank=True, max_length=100, null=True)),
                ('medicinas', models.ManyToManyField(to='pacientes.medicina')),
            ],
        ),
    ]
