# Generated by Django 2.2.6 on 2019-11-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20191112_0009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='medicina',
        ),
        migrations.AlterField(
            model_name='expediente',
            name='medicinas',
            field=models.ManyToManyField(to='medicine.medicina'),
        ),
    ]
